image: ruby:2.4.2

stages:
  - deploy
  - build
  - review
  - stage
  - production
 

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'



build_job:
  image: docker:latest
  stage: build
  script:
    - echo 'Building'
    - docker build -t reddit:latest .





branch review:
  image: jonatanblue/gitlab-ci-terraform:latest
  stage: deploy
  script: 
    - echo "Deploy" 
    - cd terraform
    - pwd
    - terraform init
    - terraform --version
    - terraform plan
    - terraform apply
     
 
 


 
  
staging:
  stage: stage
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com
production:
  stage: production
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com  