image: ruby:2.4.2

stages:
  - build
  - test
  - deploy
  - review
  - stage
  - production
 

variables:
  DATABASE_URL: 'mongodb://mongo/user_posts'



build_job:
  image: docker:latest
  stage: build
  script:
    - echo 'Building'
    - docker build -t reddit:latest .





branch review:
  image: alpine:latest
  
  stage: deploy
  script: 
    - echo "Deploy to $CI_ENVIRONMENT_SLUG" 
    - apk add --update py-pip
    - pip install docker-compose
    - docker-compose -f docker-compose.yml up
    - docker-compose ps
     
  
  
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    on_stop: stop_branch
    url: http://$CI_ENVIRONMENT_SLUG.example


stop_branch:
  script: echo Delete My App
  when: manual
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    action: stop
    
  only:
    - branches
  except:
    - master
  
staging:
  stage: stage
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: stage
    url: https://beta.example.com
production:
  stage: production
  when: manual
  script:
    - echo 'Deploy'
  environment:
    name: production
    url: https://example.com  