version: '2'
services:

   gitlab-runner:
     container_name: gitlab-runner2
     image: gitlab/gitlab-runner:latest
     volumes:
     - /srv/gitlab-runner2/data:/home/gitlab_ci_multi_runner/data
     - /srv/gitlab-runner2/config:/etc/gitlab-runner2
     - /var/run/docker.sock:/var/run/docker.sock:rw
     restart: always
   